/**
 * GamiWord Pro - システム英単語 Ch.1 全174語 完全データ
 */
const SYSTEM_WORDS_PRESET = [
  {id:'sys_1',english:'follow',phonetic:'/ˈfɑːloʊ/',japanese:'～の後に続く、従う',exampleEng:'follow her advice',exampleJap:'彼女の助言に従う',derivatives:[{english:'following',partOfSpeech:'形',japanese:'次の、以下のような'}],choices:[{text:'～の後に続く、従う',isCorrect:true},{text:'～を矢のように放つ',isCorrect:false,type:'spelling'},{text:'～を不必要に繰り返す',isCorrect:false,type:'nuance'},{text:'～を不当に非難する',isCorrect:false,type:'distractor'}]},
  {id:'sys_2',english:'consider',phonetic:'/kənˈsɪdər/',japanese:'～を考慮する、考える',exampleEng:'consider the problem seriously',exampleJap:'真剣にその問題を考える',derivatives:[{english:'consideration',partOfSpeech:'名',japanese:'考慮、思いやり'},{english:'considerate',partOfSpeech:'形',japanese:'思いやりのある'}],choices:[{text:'～を考慮する、考える',isCorrect:true},{text:'～を不当に差別する',isCorrect:false,type:'spelling'},{text:'～について何となく思い浮かべる',isCorrect:false,type:'nuance'},{text:'～を決定する',isCorrect:false,type:'distractor'}]},
  {id:'sys_3',english:'increase',phonetic:'/ɪnˈkriːs/',japanese:'増える、～を増やす',exampleEng:'increase by 20%',exampleJap:'20%増加する',derivatives:[{english:'increasingly',partOfSpeech:'副',japanese:'ますます'}],choices:[{text:'増える、～を増やす',isCorrect:true},{text:'～にインクを塗る',isCorrect:false,type:'spelling'},{text:'～を急速に2倍にする',isCorrect:false,type:'nuance'},{text:'～を供給する',isCorrect:false,type:'distractor'}]},
  {id:'sys_4',english:'expect',phonetic:'/ɪkˈspekt/',japanese:'～を予期する、期待する',exampleEng:'expect you to arrive soon',exampleJap:'君がすぐ着くことを予期する',derivatives:[{english:'expectation',partOfSpeech:'名',japanese:'予期、期待'}],choices:[{text:'～を予期する、期待する',isCorrect:true},{text:'～を除外する、除く',isCorrect:false,type:'spelling'},{text:'～を過剰に心配して待つ',isCorrect:false,type:'nuance'},{text:'～と提案する',isCorrect:false,type:'distractor'}]},
  {id:'sys_5',english:'decide',phonetic:'/dɪˈsaɪd/',japanese:'～することを決定する、判断する',exampleEng:'decide to tell the truth',exampleJap:'真実を語る決意をする',derivatives:[{english:'decision',partOfSpeech:'名',japanese:'決意、決定'},{english:'decisive',partOfSpeech:'形',japanese:'決定的な、断固とした'}],choices:[{text:'～することを決定する、判断する',isCorrect:true},{text:'～を欺く、だます',isCorrect:false,type:'spelling'},{text:'～を何となく決める',isCorrect:false,type:'nuance'},{text:'～を必要とする',isCorrect:false,type:'distractor'}]},
  {id:'sys_6',english:'develop',phonetic:'/dɪˈveləp/',japanese:'～を発達させる、開発する',exampleEng:'develop a unique ability',exampleJap:'特殊な能力を発達させる',derivatives:[{english:'development',partOfSpeech:'名',japanese:'発達、成長、開発'}],choices:[{text:'～を発達させる、開発する',isCorrect:true},{text:'～を包む、封入する',isCorrect:false,type:'spelling'},{text:'～を一時的に良くする',isCorrect:false,type:'nuance'},{text:'～を向上させる',isCorrect:false,type:'distractor'}]},
  {id:'sys_7',english:'provide',phonetic:'/prəˈvaɪd/',japanese:'～を供給する、与える',exampleEng:'provide him with information',exampleJap:'彼に情報を与える',derivatives:[{english:'provision',partOfSpeech:'名',japanese:'供給、用意'}],choices:[{text:'～を供給する、与える',isCorrect:true},{text:'～を証明する',isCorrect:false,type:'spelling'},{text:'～を無理やり貸し出す',isCorrect:false,type:'nuance'},{text:'～をさまたげる',isCorrect:false,type:'distractor'}]},
  {id:'sys_8',english:'continue',phonetic:'/kənˈtɪnjuː/',japanese:'続く、～を続ける',exampleEng:'continue to grow fast',exampleJap:'急速に成長し続ける',derivatives:[{english:'continuous',partOfSpeech:'形',japanese:'絶え間ない、休みない'}],choices:[{text:'続く、～を続ける',isCorrect:true},{text:'～を収容する',isCorrect:false,type:'spelling'},{text:'～を断続的に繰り返す',isCorrect:false,type:'nuance'},{text:'～を共有する',isCorrect:false,type:'distractor'}]},
  {id:'sys_9',english:'include',phonetic:'/ɪnˈkluːd/',japanese:'～を含む、含める',exampleEng:'The list includes his name.',exampleJap:'リストは彼の名前を含んでいる',derivatives:[{english:'including',partOfSpeech:'前',japanese:'～を含めて'}],choices:[{text:'～を含む、含める',isCorrect:true},{text:'～を除外する',isCorrect:false,type:'spelling'},{text:'～を一時的に閉じ込める',isCorrect:false,type:'nuance'},{text:'～と提案する',isCorrect:false,type:'distractor'}]},
  {id:'sys_10',english:'remain',phonetic:'/rɪˈmeɪn/',japanese:'～のままでいる、残る',exampleEng:'remain silent',exampleJap:'黙ったままでいる',derivatives:[{english:'remains',partOfSpeech:'名',japanese:'遺物、遺跡、残り物'}],choices:[{text:'～のままでいる、残る',isCorrect:true},{text:'～を思い起こさせる',isCorrect:false,type:'spelling'},{text:'～にずっととどまり続ける',isCorrect:false,type:'nuance'},{text:'～を支持する',isCorrect:false,type:'distractor'}]},
  {id:'sys_11',english:'reach',phonetic:'/riːtʃ/',japanese:'～に着く、達する',exampleEng:'reach the mountain top',exampleJap:'山頂に到達する',choices:[{text:'～に着く、達する',isCorrect:true},{text:'～に反応する',isCorrect:false,type:'spelling'},{text:'～の手前に接近する',isCorrect:false,type:'nuance'},{text:'～を傷つける',isCorrect:false,type:'distractor'}]},
  {id:'sys_12',english:'allow',phonetic:'/əˈlaʊ/',japanese:'～を許可する、許す、可能にする',exampleEng:'allow him to go out',exampleJap:'彼に外出を許可する',derivatives:[{english:'allowance',partOfSpeech:'名',japanese:'手当、小遣い'}],choices:[{text:'～を許可する、許す、可能にする',isCorrect:true},{text:'～を矢のように放つ',isCorrect:false,type:'spelling'},{text:'～を不本意ながら認める',isCorrect:false,type:'nuance'},{text:'～を強制する',isCorrect:false,type:'distractor'}]},
  {id:'sys_13',english:'force',phonetic:'/fɔːrs/',japanese:'～を強制する',exampleEng:'be forced to work',exampleJap:'働くよう強制される',choices:[{text:'～を強制する',isCorrect:true},{text:'～を偽造する',isCorrect:false,type:'spelling'},{text:'～を間接的に促す',isCorrect:false,type:'nuance'},{text:'～をあつかう',isCorrect:false,type:'distractor'}]},
  {id:'sys_14',english:'offer',phonetic:'/ˈɔːfər/',japanese:'～を申し出る、与える',exampleEng:'offer help to the poor',exampleJap:'貧しい人に援助を申し出る',choices:[{text:'～を申し出る、与える',isCorrect:true},{text:'～に苦痛を与える',isCorrect:false,type:'spelling'},{text:'～を無理やり押し付ける',isCorrect:false,type:'nuance'},{text:'～を向上させる',isCorrect:false,type:'distractor'}]},
  {id:'sys_15',english:'realize',phonetic:'/ˈriːəlaɪz/',japanese:'～を悟る、気づく、実現する',exampleEng:'realize the error',exampleJap:'まちがいを悟る',derivatives:[{english:'realization',partOfSpeech:'名',japanese:'認識、実現'}],choices:[{text:'～を悟る、気づく、実現する',isCorrect:true},{text:'～を解放する',isCorrect:false,type:'spelling'},{text:'～をなんとなく直感する',isCorrect:false,type:'nuance'},{text:'～を認める',isCorrect:false,type:'distractor'}]},
  
  // 16〜174：起動時に疑似AI、あるいはOpenAI API経由で自動生成されて永続化されます。
  {id:'sys_16',english:'suggest',phonetic:'/səɡˈdʒest/',japanese:'～と提案する、ほのめかす',exampleEng:'suggest a new way',exampleJap:'新しいやり方を提案する',derivatives:[{english:'suggestion',partOfSpeech:'名',japanese:'提案、暗示'}]},
  {id:'sys_17',english:'require',phonetic:'/rɪˈkwaɪər/',japanese:'～を必要とする、要求する',exampleEng:'require more attention',exampleJap:'もっと注意を必要とする',derivatives:[{english:'requirement',partOfSpeech:'名',japanese:'要求されるもの、必要条件'}]},
  {id:'sys_18',english:'worry',phonetic:'/ˈwɜːri/',japanese:'心配する、～に心配させる',exampleEng:'worry about money',exampleJap:'お金のことを心配する',derivatives:[{english:'worried',partOfSpeech:'形',japanese:'心配している'}]},
  {id:'sys_19',english:'wonder',phonetic:'/ˈwʌndər/',japanese:'～かと疑問に思う、驚く',exampleEng:'wonder where he has gone',exampleJap:'彼はどこに行ったのかと思う',derivatives:[{english:'wonderful',partOfSpeech:'形',japanese:'すばらしい'}]},
  {id:'sys_20',english:'cost',phonetic:'/kɔːst/',japanese:'（費用）を要する、～を奪う',exampleEng:'The car cost me $50,000.',exampleJap:'その車には5万ドルかかった',derivatives:[{english:'costly',partOfSpeech:'形',japanese:'高価な、損失の大きい'}]},
  {id:'sys_21',english:'tend',phonetic:'/tend/',japanese:'Vする傾向がある、Vしがちである',exampleEng:'tend to get angry',exampleJap:'腹を立てがちである',derivatives:[{english:'tendency',partOfSpeech:'名',japanese:'傾向、癖'}]},
  {id:'sys_22',english:'depend',phonetic:'/dɪˈpend/',japanese:'Aに依存する、Aしだいで決まる',exampleEng:'Everything depends on him.',exampleJap:'すべては彼しだいだ',derivatives:[{english:'dependent',partOfSpeech:'形',japanese:'依存する'},{english:'dependence',partOfSpeech:'名',japanese:'依存'}]},
  {id:'sys_23',english:'share',phonetic:'/ʃeər/',japanese:'～を分け合う、共有する',exampleEng:'share a room with a friend',exampleJap:'友人と部屋を共有する'},
  {id:'sys_24',english:'demand',phonetic:'/dɪˈmænd/',japanese:'～を要求する、必要とする',exampleEng:'demand more freedom',exampleJap:'もっと自由を要求する',derivatives:[{english:'demanding',partOfSpeech:'形',japanese:'要求の厳しい'}]},
  {id:'sys_25',english:'support',phonetic:'/səˈpɔːrt/',japanese:'～を支持する、援助する、養う',exampleEng:'support the president',exampleJap:'大統領を支持する'},
  {id:'sys_26',english:'hire',phonetic:'/ˈhaɪər/',japanese:'～を雇う、借りる',exampleEng:'hire many young people',exampleJap:'多くの若者を雇う'},
  {id:'sys_27',english:'regard',phonetic:'/rɪˈɡɑːrd/',japanese:'AをBと思う、みなす',exampleEng:'regard him as a friend',exampleJap:'彼を友達とみなす',derivatives:[{english:'regarding',partOfSpeech:'前',japanese:'～に関して'},{english:'regardless',partOfSpeech:'形',japanese:'関係なく'}]},
  {id:'sys_28',english:'base',phonetic:'/beɪs/',japanese:'AがBに基づいている',exampleEng:'This story is based on fact.',exampleJap:'この話は事実に基づいている',derivatives:[{english:'basic',partOfSpeech:'形',japanese:'基礎的な'}]},
  {id:'sys_29',english:'improve',phonetic:'/ɪmˈpruːv/',japanese:'～を向上させる、改善する',exampleEng:'improve living conditions',exampleJap:'生活状態を向上させる',derivatives:[{english:'improvement',partOfSpeech:'名',japanese:'進歩、改善'}]},
  {id:'sys_30',english:'recognize',phonetic:'/ˈrekəɡnaɪz/',japanese:'～を認める、識別する',exampleEng:'recognize the importance',exampleJap:'重要性を認める',derivatives:[{english:'recognition',partOfSpeech:'名',japanese:'認識、承認'}]},
  {id:'sys_31',english:'notice',phonetic:'/ˈnoʊtɪs/',japanese:'～に気づく、～だとわかる',exampleEng:'notice the color change',exampleJap:'色彩の変化に気づく',derivatives:[{english:'noticeable',partOfSpeech:'形',japanese:'目立つ、著しい'}]},
  {id:'sys_32',english:'suppose',phonetic:'/səˈpoʊz/',japanese:'～だと思う、想像する、仮定する',exampleEng:'You are supposed to wear a seat belt.',exampleJap:'シートベルトを締めることになっている'},
  {id:'sys_33',english:'raise',phonetic:'/reɪz/',japanese:'～を上げる、育てる、提起する',exampleEng:'raise both hands',exampleJap:'両手を上げる'},
  {id:'sys_34',english:'prefer',phonetic:'/prɪˈfɜːr/',japanese:'～をより好む',exampleEng:'prefer tea to coffee',exampleJap:'コーヒーよりお茶を好む',derivatives:[{english:'preference',partOfSpeech:'名',japanese:'好み、好物'}]},
  {id:'sys_35',english:'cheer',phonetic:'/tʃɪər/',japanese:'～を励ます、声援する',exampleEng:'cheer up the patients',exampleJap:'患者たちを元気づける',derivatives:[{english:'cheerful',partOfSpeech:'形',japanese:'陽気な'}]},
  {id:'sys_36',english:'suffer',phonetic:'/ˈsʌfər/',japanese:'（苦痛など）を経験する、苦しむ',exampleEng:'suffer heavy damage',exampleJap:'ひどい損害を受ける',derivatives:[{english:'suffering',partOfSpeech:'名',japanese:'苦しみ'}]},
  {id:'sys_37',english:'describe',phonetic:'/dɪˈskraɪb/',japanese:'～を描写する、特徴を説明する',exampleEng:'describe the lost bag',exampleJap:'なくしたバッグの特徴を言う',derivatives:[{english:'description',partOfSpeech:'名',japanese:'描写、説明'}]},
  {id:'sys_38',english:'prevent',phonetic:'/prɪˈvent/',japanese:'～をさまたげる、防ぐ、させない',exampleEng:'prevent him from sleeping',exampleJap:'彼が眠るのをさまたげる',derivatives:[{english:'prevention',partOfSpeech:'名',japanese:'防止、予防'}]},
  {id:'sys_39',english:'reduce',phonetic:'/rɪˈduːs/',japanese:'～を減らす、変える',exampleEng:'reduce energy costs',exampleJap:'エネルギー費を減らす',derivatives:[{english:'reduction',partOfSpeech:'名',japanese:'減少、削減'}]},
  {id:'sys_40',english:'mistake',phonetic:'/mɪˈsteɪk/',japanese:'～を誤解する、まちがえる',exampleEng:'mistake salt for sugar',exampleJap:'塩を砂糖とまちがえる',derivatives:[{english:'mistaken',partOfSpeech:'形',japanese:'誤った、まちがっている'}]},
  {id:'sys_41',english:'prepare',phonetic:'/prɪˈpeər/',japanese:'準備をする、用意する',exampleEng:'prepare a room for a guest',exampleJap:'客のために部屋を準備する',derivatives:[{english:'preparation',partOfSpeech:'名',japanese:'準備、用意'}]},
  {id:'sys_42',english:'encourage',phonetic:'/ɪnˈkɜːrɪdʒ/',japanese:'～をはげます、促進する',exampleEng:'encourage children to read',exampleJap:'子供に読書をすすめる',derivatives:[{english:'encouragement',partOfSpeech:'名',japanese:'はげまし、促進'}]},
  {id:'sys_43',english:'prove',phonetic:'/pruːv/',japanese:'～だとわかる、証明する',exampleEng:'prove to be true',exampleJap:'本当だとわかる',derivatives:[{english:'proof',partOfSpeech:'名',japanese:'証拠、証明'}]},
  {id:'sys_44',english:'treat',phonetic:'/triːt/',japanese:'～をあつかう、手当てする、おごる',exampleEng:'treat him like a child',exampleJap:'子供みたいに彼をあつかう',derivatives:[{english:'treatment',partOfSpeech:'名',japanese:'取り扱い、治療'}]},
  {id:'sys_45',english:'establish',phonetic:'/ɪˈstæblɪʃ/',japanese:'～を設立する、創立する、確定する',exampleEng:'establish a company',exampleJap:'会社を設立する',derivatives:[{english:'establishment',partOfSpeech:'名',japanese:'施設、組織、設立'}]},
  {id:'sys_46',english:'relate',phonetic:'/rɪˈleɪt/',japanese:'関係がある、関係づける',exampleEng:'stress-related illness',exampleJap:'ストレスと関係のある病気',derivatives:[{english:'relation',partOfSpeech:'名',japanese:'関係'},{english:'relationship',partOfSpeech:'名',japanese:'関係'}]},
  {id:'sys_47',english:'compare',phonetic:'/kəmˈpeər/',japanese:'～を比較する、たとえる',exampleEng:'compare Japan with China',exampleJap:'日本と中国を比較する',derivatives:[{english:'comparison',partOfSpeech:'名',japanese:'比較、たとえ'}]},
  {id:'sys_48',english:'spread',phonetic:'/spred/',japanese:'～を広げる、広がる',exampleEng:'spread the tablecloth',exampleJap:'テーブルクロスを広げる'},
  {id:'sys_49',english:'refer',phonetic:'/rɪˈfɜːr/',japanese:'～を指し示す、言及する、参照する',exampleEng:'What does this word refer to?',exampleJap:'この語は何を指示するか',derivatives:[{english:'reference',partOfSpeech:'名',japanese:'言及、参照'}]},
  {id:'sys_50',english:'supply',phonetic:'/səˈplaɪ/',japanese:'～を供給する、支給する',exampleEng:'supply the city with water',exampleJap:'その都市に水を供給する'},
  {id:'sys_51',english:'gain',phonetic:'/ɡeɪn/',japanese:'～を得る、もうける、増やす',exampleEng:'gain useful knowledge',exampleJap:'有益な知識を得る'},
  {id:'sys_52',english:'destroy',phonetic:'/dɪˈstrɔɪ/',japanese:'～を破壊する、滅ぼす',exampleEng:'destroy forests',exampleJap:'森林を破壊する',derivatives:[{english:'destruction',partOfSpeech:'名',japanese:'破壊、破滅'}]},
  {id:'sys_53',english:'apply',phonetic:'/əˈlaɪ/',japanese:'当てはめる、応用する、申し込む',exampleEng:'apply the rule to every case',exampleJap:'全てのケースに規則を当てはめる',derivatives:[{english:'application',partOfSpeech:'名',japanese:'応用、適用、申し込み'}]},
  {id:'sys_54',english:'seek',phonetic:'/siːk/',japanese:'～を求める、得ようとする',exampleEng:'seek help from the police',exampleJap:'警察に助けを求める'},
  {id:'sys_55',english:'search',phonetic:'/sɜːrtʃ/',japanese:'～を探す、探る',exampleEng:'search for the stolen car',exampleJap:'盗難車を探す'},
  {id:'sys_56',english:'claim',phonetic:'/kleɪm/',japanese:'～と主張する、言い張る、要求する',exampleEng:'He claims that he saw a UFO.',exampleJap:'彼はUFOを見たと主張する'},
  {id:'sys_57',english:'draw',phonetic:'/drɔː/',japanese:'～を引っ張る、引き出す、描く',exampleEng:'draw a map',exampleJap:'地図を描く',derivatives:[{english:'drawer',partOfSpeech:'名',japanese:'引き出し'}]},
  {id:'sys_58',english:'refuse',phonetic:'/rɪˈfjuːz/',japanese:'～を断る、辞退する',exampleEng:'refuse to give up hope',exampleJap:'希望を捨てるのを拒む',derivatives:[{english:'refusal',partOfSpeech:'名',japanese:'拒否、拒絶'}]},
  {id:'sys_59',english:'respond',phonetic:'/rɪˈspɑːnd/',japanese:'返答する、反応する',exampleEng:'respond to questions',exampleJap:'質問に答える',derivatives:[{english:'response',partOfSpeech:'名',japanese:'返答、反応'}]},
  {id:'sys_60',english:'mention',phonetic:'/ˈmenʃn/',japanese:'～について述べる、言及する',exampleEng:'Never mention it again.',exampleJap:'二度とそのことを口にするな'},
  {id:'sys_61',english:'judge',phonetic:'/dʒʌdʒ/',japanese:'～を判断する、裁判する',exampleEng:'judge a person by his looks',exampleJap:'人を見た目で判断する',derivatives:[{english:'judgment',partOfSpeech:'名',japanese:'判断'}]},
  {id:'sys_62',english:'approach',phonetic:'/əˈproʊtʃ/',japanese:'～に接近する、取り組む',exampleEng:'The plane is approaching Chicago.',exampleJap:'飛行機はシカゴに接近している'},
  {id:'sys_63',english:'admit',phonetic:'/ədˈmɪt/',japanese:'～を認める、許可する',exampleEng:'I admit that I was wrong.',exampleJap:'自分がまちがっていたと認める',derivatives:[{english:'admission',partOfSpeech:'名',japanese:'入場、入学許可'}]},
  {id:'sys_64',english:'reflect',phonetic:'/rɪˈflekt/',japanese:'～を反映する、反射する、熟考する',exampleEng:'reflect the mood of the times',exampleJap:'時代の気分を反映する',derivatives:[{english:'reflection',partOfSpeech:'名',japanese:'反射、反映、熟考'}]},
  {id:'sys_65',english:'perform',phonetic:'/pərˈfɔːrm/',japanese:'～を行う、遂行する、演じる',exampleEng:'perform the job',exampleJap:'仕事を遂行する',derivatives:[{english:'performance',partOfSpeech:'名',japanese:'遂行、演技、性能'}]},
  {id:'sys_66',english:'bore',phonetic:'/bɔːr/',japanese:'～をうんざりさせる、退屈させる',exampleEng:'a very boring movie',exampleJap:'すごく退屈な映画',derivatives:[{english:'boring',partOfSpeech:'形',japanese:'退屈な'}]},
  {id:'sys_67',english:'survive',phonetic:'/sərˈvaɪv/',japanese:'生き残る、～より長生きする',exampleEng:'survive in the jungle',exampleJap:'ジャングルで生き残る',derivatives:[{english:'survival',partOfSpeech:'名',japanese:'生存、生き残ること'}]},
  {id:'sys_68',english:'represent',phonetic:'/ˌreprɪˈzent/',japanese:'～を表す、示す、代表する',exampleEng:'words represent ideas',exampleJap:'言葉は考えを表す',derivatives:[{english:'representative',partOfSpeech:'名',japanese:'代表者'}]},
  {id:'sys_69',english:'argue',phonetic:'/ˈɑːrɡjuː/',japanese:'～と主張する、議論する、論争する',exampleEng:'argue that he is right',exampleJap:'彼は正しいと主張する',derivatives:[{english:'argument',partOfSpeech:'名',japanese:'議論、主張、論争'}]},
  {id:'sys_70',english:'grant',phonetic:'/ɡrænt/',japanese:'～を認める、与える',exampleEng:'take freedom for granted',exampleJap:'自由を当然と考える'},
  {id:'sys_71',english:'indicate',phonetic:'/ˈɪndɪkeɪt/',japanese:'～を指し示す、表す',exampleEng:'The data indicate that he is right.',exampleJap:'データは彼が正しいことを示す',derivatives:[{english:'indication',partOfSpeech:'名',japanese:'指示、暗示、兆候'}]},
  {id:'sys_72',english:'belong',phonetic:'/bɪˈlɔːŋ/',japanese:'所属している、所有物である',exampleEng:'The book belongs to Howard.',exampleJap:'その本はハワードのものだ',derivatives:[{english:'belongings',partOfSpeech:'名',japanese:'所有物、持ち物'}]},
  {id:'sys_73',english:'acquire',phonetic:'/əˈkwaɪər/',japanese:'～を習得する、獲得する',exampleEng:'acquire a language',exampleJap:'言語を習得する',derivatives:[{english:'acquisition',partOfSpeech:'名',japanese:'習得'}]},
  {id:'sys_74',english:'reply',phonetic:'/rɪˈplaɪ/',japanese:'返事をする、答える',exampleEng:'reply to his letter',exampleJap:'彼の手紙に返事をする'},
  {id:'sys_75',english:'feed',phonetic:'/fiːd/',japanese:'～にエサをやる、養う',exampleEng:'feed a large family',exampleJap:'大勢の家族を養う'},
  {id:'sys_76',english:'escape',phonetic:'/ɪˈskeɪp/',japanese:'逃げる、まぬがれる、避ける',exampleEng:'escape from reality',exampleJap:'現実から逃避する'},
  {id:'sys_77',english:'replace',phonetic:'/rɪˈpleɪs/',japanese:'～に取って代わる、取り替える',exampleEng:'replace the old system',exampleJap:'古い制度に取って代わる',derivatives:[{english:'replacement',partOfSpeech:'名',japanese:'取り替え、代用品'}]},
  {id:'sys_78',english:'reveal',phonetic:'/rɪˈviːl/',japanese:'～を明らかにする、示す',exampleEng:'reveal a surprising fact',exampleJap:'驚くべき事実を明らかにする',derivatives:[{english:'revelation',partOfSpeech:'名',japanese:'暴露、発見'}]},
  {id:'sys_79',english:'surround',phonetic:'/səˈraʊnd/',japanese:'～を取り囲む',exampleEng:'Japan is surrounded by the sea.',exampleJap:'日本は海に囲まれている',derivatives:[{english:'surroundings',partOfSpeech:'名',japanese:'環境、周囲の状況'}]},
  {id:'sys_80',english:'suit',phonetic:'/suːt/',japanese:'～に合う、適する、似合う',exampleEng:'The job suits you.',exampleJap:'その仕事は君に合っている',derivatives:[{english:'suitable',partOfSpeech:'形',japanese:'適した、ふさわしい'}]},
  {id:'sys_81',english:'estimate',phonetic:'/ˈestɪmeɪt/',japanese:'～を推定する、評価する',exampleEng:'the estimated population of Japan',exampleJap:'日本の推定人口',derivatives:[{english:'underestimate',partOfSpeech:'動',japanese:'～を過小評価する'}]},
  {id:'sys_82',english:'aim',phonetic:'/eɪm/',japanese:'～をねらう、目指す',exampleEng:'aim at the Asian market',exampleJap:'アジア市場をねらう'},
  {id:'sys_83',english:'earn',phonetic:'/ɜːrn/',japanese:'～を稼ぐ、もうける、得る',exampleEng:'earn money for the family',exampleJap:'家族のためにお金を稼ぐ'},
  {id:'sys_84',english:'decline',phonetic:'/dɪˈklaɪn/',japanese:'衰退する、低下する、辞退する',exampleEng:'My memory began to decline.',exampleJap:'記憶力が低下し始めた'},
  {id:'sys_85',english:'afford',phonetic:'/əˈfɔːrd/',japanese:'～をする余裕がある、与える',exampleEng:"can't afford to buy a Ford",exampleJap:'フォードの車を買う余裕がない',derivatives:[{english:'affordable',partOfSpeech:'形',japanese:'手ごろな値段の'}]},
  {id:'sys_86',english:'confuse',phonetic:'/kənˈfjuːz/',japanese:'～を当惑させる、混乱させる、混同する',exampleEng:'be confused by her anger',exampleJap:'彼女の怒りに当惑する',derivatives:[{english:'confusion',partOfSpeech:'名',japanese:'混乱、混同、当惑'}]},
  {id:'sys_87',english:'graduate',phonetic:'/ˈɡrædʒuət/',japanese:'Aを卒業する',exampleEng:'graduate from high school',exampleJap:'高校を卒業する',derivatives:[{english:'graduation',partOfSpeech:'名',japanese:'卒業'}]},
  {id:'sys_88',english:'vary',phonetic:'/ˈveəri/',japanese:'変わる、さまざまである、変える',exampleEng:'vary from country to country',exampleJap:'国によって変わる',derivatives:[{english:'various',partOfSpeech:'形',japanese:'さまざまな'}]},
  {id:'sys_89',english:'remove',phonetic:'/rɪˈmuːv/',japanese:'～を移す、取り去る、脱ぐ',exampleEng:'remove the cover',exampleJap:'カバーを取り除く',derivatives:[{english:'removal',partOfSpeech:'名',japanese:'除去、移動'}]},
  {id:'sys_90',english:'insist',phonetic:'/ɪnˈsɪst/',japanese:'～を強く主張する、言い張る',exampleEng:'insist on going to France',exampleJap:'フランスに行くと言い張る'},
  {id:'sys_91',english:'examine',phonetic:'/ɪɡˈzæmɪn/',japanese:'～を調査する、検査する、試験する',exampleEng:'examine every record',exampleJap:'あらゆる記録を調べる',derivatives:[{english:'examination',partOfSpeech:'名',japanese:'試験、調査'}]},
  {id:'sys_92',english:'remind',phonetic:'/rɪˈmɪnd/',japanese:'AにBのことを思い出させる',exampleEng:'remind him of the promise',exampleJap:'彼に約束を思い出させる'},
  {id:'sys_93',english:'contribute',phonetic:'/kənˈtrɪbjuːt/',japanese:'貢献する、一因となる、寄付する',exampleEng:'contribute to world peace',exampleJap:'世界平和に貢献する',derivatives:[{english:'contribution',partOfSpeech:'名',japanese:'貢献、寄付'}]},
  {id:'sys_94',english:'warn',phonetic:'/wɔːrn/',japanese:'人に警告する',exampleEng:'warn him of the danger',exampleJap:'彼に危険を警告する',derivatives:[{english:'warning',partOfSpeech:'名',japanese:'警告、警報'}]},
  {id:'sys_95',english:'connect',phonetic:'/kəˈnekt/',japanese:'～をつなぐ、関係づける、つながる',exampleEng:'connect the computer to the Internet',exampleJap:'コンピュータをインターネットにつなぐ',derivatives:[{english:'connection',partOfSpeech:'名',japanese:'結びつき、関係'}]},
  {id:'sys_96',english:'match',phonetic:'/mætʃ/',japanese:'～に匹敵する、～と調和する',exampleEng:'match him in power',exampleJap:'力で彼に匹敵する'},
  {id:'sys_97',english:'focus',phonetic:'/ˈfoʊkəs/',japanese:'焦点を合わせる、集中する',exampleEng:'focus on the problem',exampleJap:'その問題に焦点を合わせる'},
  {id:'sys_98',english:'reject',phonetic:'/rɪˈdʒekt/',japanese:'～を断る、拒絶する',exampleEng:'reject the proposal',exampleJap:'提案を拒絶する',derivatives:[{english:'rejection',partOfSpeech:'名',japanese:'拒絶、拒否'}]},
  {id:'sys_99',english:'convince',phonetic:'/kənˈvɪns/',japanese:'人を納得させる、確信させる',exampleEng:'convince him that it is true',exampleJap:'それは本当だと彼に確信させる',derivatives:[{english:'conviction',partOfSpeech:'名',japanese:'確信'}]},
  {id:'sys_100',english:'associate',phonetic:'/əˈsoʊʃieɪt/',japanese:'AをBに関連づける、連想する',exampleEng:'Health is associated with happiness.',exampleJap:'健康は幸福と関連している',derivatives:[{english:'association',partOfSpeech:'名',japanese:'協会、連想、交際'}]},
  {id:'sys_101',english:'rush',phonetic:'/rʌʃ/',japanese:'急いで行く、急いでやる',exampleEng:'rush into the hospital',exampleJap:'病院へ急いで行く'},
  {id:'sys_102',english:'stress',phonetic:'/stres/',japanese:'～を強調する',exampleEng:'stress the need for information',exampleJap:'情報の必要性を強調する',derivatives:[{english:'stressful',partOfSpeech:'形',japanese:'ストレスの多い'}]},
  {id:'sys_103',english:'attract',phonetic:'/əˈtrækt/',japanese:'引きつける、魅惑する',exampleEng:'attract his attention',exampleJap:'彼の注意を引きつける',derivatives:[{english:'attractive',partOfSpeech:'形',japanese:'魅力的な'},{english:'attraction',partOfSpeech:'名',japanese:'魅力、引きつけるもの'}]},
  {id:'sys_104',english:'rely',phonetic:'/rɪˈlaɪ/',japanese:'Aに頼る、信頼する',exampleEng:'rely on their power',exampleJap:'彼らの力に頼る',derivatives:[{english:'reliable',partOfSpeech:'形',japanese:'信頼できる、当てになる'}]},
  {id:'sys_105',english:'regret',phonetic:'/rɪˈɡret/',japanese:'～を後悔する、残念に思う',exampleEng:'regret leaving home',exampleJap:'家を出たのを後悔する',derivatives:[{english:'regrettable',partOfSpeech:'形',japanese:'残念な、悔やまれる'}]},
  {id:'sys_106',english:'adopt',phonetic:'/əˈdɑːpt/',japanese:'～を採用する、養子にする',exampleEng:'adopt a new system',exampleJap:'新しいシステムを採用する',derivatives:[{english:'adoption',partOfSpeech:'名',japanese:'採用、養子縁組'}]},
  {id:'sys_107',english:'shake',phonetic:'/ʃeɪk/',japanese:'～を振る、震える、動揺させる',exampleEng:'shake the bottle well',exampleJap:'ビンをよく振る'},
  {id:'sys_108',english:'hurt',phonetic:'/hɜːrt/',japanese:'～を傷つける、痛む',exampleEng:'hurt her feelings',exampleJap:'彼女の気持ちを傷つける'},
  {id:'sys_109',english:'operate',phonetic:'/ˈɑːpəreɪt/',japanese:'作動する、～を操作する、手術する',exampleEng:'operate a computer with a mouse',exampleJap:'マウスでコンピュータを操作する',derivatives:[{english:'operation',partOfSpeech:'名',japanese:'操作、手術、活動'}]},
  {id:'sys_110',english:'extend',phonetic:'/ɪkˈstend/',japanese:'～を広げる、延長する、伸びる',exampleEng:'Exercise extends life.',exampleJap:'運動は寿命を延ばす',derivatives:[{english:'extent',partOfSpeech:'名',japanese:'程度、範囲'}]},
  {id:'sys_111',english:'blame',phonetic:'/bleɪm/',japanese:'～を非難する、～のせいにする',exampleEng:'blame others for the failure',exampleJap:'失敗を他人のせいにする'},
  {id:'sys_112',english:'consist',phonetic:'/kənˈsɪst/',japanese:'Aで構成されている、存在している',exampleEng:'The book consists of six lessons.',exampleJap:'その本は6課で構成されている'},
  {id:'sys_113',english:'persuade',phonetic:'/pərˈsweɪd/',japanese:'～を説得する、信じさせる',exampleEng:'persuade them to go back',exampleJap:'彼らを説得して帰らせる',derivatives:[{english:'persuasion',partOfSpeech:'名',japanese:'説得'}]},
  {id:'sys_114',english:'admire',phonetic:'/ədˈmaɪər/',japanese:'～に感心する、賞賛する、尊敬する',exampleEng:'admire her work',exampleJap:'彼女の仕事に感心する',derivatives:[{english:'admiration',partOfSpeech:'名',japanese:'感心、賞賛'}]},
  {id:'sys_115',english:'disappoint',phonetic:'/ˌdɪsəˈpɔɪnt/',japanese:'～を失望させる',exampleEng:'be disappointed with the test results',exampleJap:'試験の結果に失望する',derivatives:[{english:'disappointment',partOfSpeech:'名',japanese:'失望'}]},
  {id:'sys_116',english:'expand',phonetic:'/ɪkˈspænd/',japanese:'～を拡大する、増大する、膨張する',exampleEng:'expand business overseas',exampleJap:'海外へ事業を拡大する',derivatives:[{english:'expansion',partOfSpeech:'名',japanese:'拡大、進展'}]},
  {id:'sys_117',english:'preserve',phonetic:'/prɪˈzɜːrv/',japanese:'～を保護する、保存する、維持する',exampleEng:'preserve forests',exampleJap:'森林を保護する',derivatives:[{english:'preservation',partOfSpeech:'名',japanese:'保護、保存、維持'}]},
  {id:'sys_118',english:'struggle',phonetic:'/ˈstrʌɡl/',japanese:'苦闘する、努力する、もがく',exampleEng:'struggle to get free',exampleJap:'自由になろうともがく'},
  {id:'sys_119',english:'arrange',phonetic:'/əˈreɪndʒ/',japanese:'手はずを整える、手配する、配列する',exampleEng:'arrange the meeting',exampleJap:'会合の手はずを整える',derivatives:[{english:'arrangement',partOfSpeech:'名',japanese:'準備、整理、配列'}]},
  {id:'sys_120',english:'disturb',phonetic:'/dɪˈstɜːrb/',japanese:'～をさまたげる、不安にする',exampleEng:'disturb his sleep',exampleJap:'彼の睡眠をさまたげる',derivatives:[{english:'disturbance',partOfSpeech:'名',japanese:'混乱、妨害'}]},
  {id:'sys_121',english:'employ',phonetic:'/ɪmˈplɔɪ/',japanese:'～を雇う、用いる',exampleEng:'employ foreign workers',exampleJap:'外国人労働者を雇う',derivatives:[{english:'employee',partOfSpeech:'名',japanese:'従業員'},{english:'employment',partOfSpeech:'名',japanese:'雇用、職'}]},
  {id:'sys_122',english:'engage',phonetic:'/ɪnˈɡeɪdʒ/',japanese:'Aに従事する、参加する、従事させる',exampleEng:'engage in volunteer activities',exampleJap:'ボランティア活動に従事する',derivatives:[{english:'engagement',partOfSpeech:'名',japanese:'約束、婚約'}]},
  {id:'sys_123',english:'abandon',phonetic:'/əˈbændən/',japanese:'～を捨てる、放棄する',exampleEng:'an abandoned pet',exampleJap:'捨てられたペット'},
  {id:'sys_124',english:'display',phonetic:'/dɪˈspleɪ/',japanese:'～を展示する、表す、表示する',exampleEng:'display prices',exampleJap:'価格を示す'},
  {id:'sys_125',english:'encounter',phonetic:'/ɪnˈkaʊntər/',japanese:'～に偶然出会う、遭う、ぶつかる',exampleEng:'encounter many difficulties',exampleJap:'数々の困難に出会う'},
  {id:'sys_126',english:'amuse',phonetic:'/əˈmjuːz/',japanese:'～を楽しませる、笑わせる',exampleEng:'amuse students with jokes',exampleJap:'冗談で学生を笑わせる',derivatives:[{english:'amusing',partOfSpeech:'形',japanese:'ゆかいな、楽しい'}]},
  {id:'sys_127',english:'bother',phonetic:'/ˈbɑːðər/',japanese:'面倒をかける、気にする',exampleEng:'Sorry to bother you, but...',exampleJap:'おじゃましてすみませんが…'},
  {id:'sys_128',english:'concentrate',phonetic:'/ˈkɑːnsntreɪt/',japanese:'集中する、集中させる',exampleEng:'concentrate on what he is saying',exampleJap:'彼の話に集中する',derivatives:[{english:'concentration',partOfSpeech:'名',japanese:'集中、専念'}]},
  {id:'sys_129',english:'adapt',phonetic:'/əˈdæpt/',japanese:'～を適応させる、適応する、改変する',exampleEng:'adapt to a new culture',exampleJap:'新しい文化に適応する',derivatives:[{english:'adaptation',partOfSpeech:'名',japanese:'適応、順順'}]},
  {id:'sys_130',english:'puzzle',phonetic:'/ˈpʌzl/',japanese:'～を当惑させる、困らせる',exampleEng:'be puzzled by the problem',exampleJap:'その問題に頭を悩ませる',derivatives:[{english:'puzzled',partOfSpeech:'形',japanese:'当惑して'}]},
  {id:'sys_131',english:'appeal',phonetic:'/əˈpiːl/',japanese:'Aに訴えかける、引きつける',exampleEng:'appeal to his feelings',exampleJap:'彼の感情に訴えかける',derivatives:[{english:'appealing',partOfSpeech:'形',japanese:'魅力的な'}]},
  {id:'sys_132',english:'combine',phonetic:'/kəmˈbaɪn/',japanese:'～を結合させる、組み合わせる',exampleEng:'combine song and dance',exampleJap:'歌と踊りを組み合わせる',derivatives:[{english:'combination',partOfSpeech:'名',japanese:'結合、組み合わせ'}]},
  {id:'sys_133',english:'delay',phonetic:'/dɪˈleɪ/',japanese:'～を遅らせる、延期する',exampleEng:'delay his arrival',exampleJap:'彼の到着を遅らせる'},
  {id:'sys_134',english:'repair',phonetic:'/rɪˈpeər/',japanese:'～を修理する、修復する',exampleEng:'repair the car',exampleJap:'車を修理する'},
  {id:'sys_135',english:'fascinate',phonetic:'/ˈfæsɪneɪt/',japanese:'人を夢中にさせる、興味をかきたてる',exampleEng:'a fascinating story',exampleJap:'夢中にさせる物語',derivatives:[{english:'fascinating',partOfSpeech:'形',japanese:'魅惑的な、非常におもしろい'}]},
  {id:'sys_136',english:'pardon',phonetic:'/ˈpɑːrdn/',japanese:'～を許す',exampleEng:'Pardon me.',exampleJap:'ごめんなさい'},
  {id:'sys_137',english:'import',phonetic:'/ˈɪmpɔːrt/',japanese:'～を輸入する',exampleEng:'import food from abroad',exampleJap:'海外から食料を輸入する'},
  {id:'sys_138',english:'remark',phonetic:'/rɪˈmɑːrk/',japanese:'～と述べる、言う',exampleEng:'remark that he is kind',exampleJap:'彼は親切だと述べる',derivatives:[{english:'remarkable',partOfSpeech:'形',japanese:'注目すべき、珍しい'}]},
  {id:'sys_139',english:'reserve',phonetic:'/rɪˈzɜːrv/',japanese:'～を予約する、とっておく',exampleEng:'reserve a room at a hotel',exampleJap:'ホテルの部屋を予約する',derivatives:[{english:'reservation',partOfSpeech:'名',japanese:'予約、指定'}]},
  {id:'sys_140',english:'amaze',phonetic:'/əˈmeɪz/',japanese:'～を驚嘆させる',exampleEng:'at an amazing speed',exampleJap:'驚異的な速さで',derivatives:[{english:'amazing',partOfSpeech:'形',japanese:'驚くべき、見事な'}]},
  {id:'sys_141',english:'frighten',phonetic:'/ˈfraɪtn/',japanese:'人におびえさせる、ぞっとさせる',exampleEng:'a frightening experience',exampleJap:'ぞっとするような経験',derivatives:[{english:'frightening',partOfSpeech:'形',japanese:'ぞっとするような'}]},
  {id:'sys_142',english:'release',phonetic:'/rɪˈliːs/',japanese:'～を解放する、発表する、放出する',exampleEng:'release him from work',exampleJap:'仕事から彼を解放する'},
  {id:'sys_143',english:'rent',phonetic:'/rent/',japanese:'～を賃借りする、賃貸しする',exampleEng:'rent an apartment',exampleJap:'アパートを借りる'},
  {id:'sys_144',english:'recover',phonetic:'/rɪˈkʌvər/',japanese:'回復する、取り戻す',exampleEng:'recover from illness',exampleJap:'病気から回復する',derivatives:[{english:'recovery',partOfSpeech:'名',japanese:'回復、取り戻すこと'}]},
  {id:'sys_145',english:'suspect',phonetic:'/səˈspekt/',japanese:'～ではないかと思う、疑う',exampleEng:'I suspect that he is a spy.',exampleJap:'私は彼がスパイではないかと思う',derivatives:[{english:'suspicion',partOfSpeech:'名',japanese:'容疑、疑い'}]},
  {id:'sys_146',english:'deliver',phonetic:'/dɪˈlɪvər/',japanese:'～を配達する、渡す、演説をする',exampleEng:'deliver a message to a friend',exampleJap:'友人に伝言を渡す',derivatives:[{english:'delivery',partOfSpeech:'名',japanese:'配達'}]},
  {id:'sys_147',english:'identify',phonetic:'/aɪˈdentɪfaɪ/',japanese:'正体をつきとめる、共感する、同一視する',exampleEng:'identify people by their eyes',exampleJap:'目で人の本人確認をする',derivatives:[{english:'identity',partOfSpeech:'名',japanese:'身元、正体、独自性'}]},
  {id:'sys_148',english:'locate',phonetic:'/ˈloʊkeɪt/',japanese:'位置する、場所を見つける',exampleEng:'The office is located in the area.',exampleJap:'オフィスはその地域にある',derivatives:[{english:'location',partOfSpeech:'名',japanese:'位置、場所'}]},
  {id:'sys_149',english:'manufacture',phonetic:'/ˌmænjuˈfæktʃər/',japanese:'～を製造する、生産する',exampleEng:'a car manufacturing company',exampleJap:'車を製造する会社',derivatives:[{english:'manufacturer',partOfSpeech:'名',japanese:'製造業者、メーカー'}]},
  {id:'sys_150',english:'occupy',phonetic:'/ˈːkjupaɪ/',japanese:'場所・地位などを占める',exampleEng:'occupy a high position',exampleJap:'高い地位を占める'},
  {id:'sys_151',english:'own',phonetic:'/oʊn/',japanese:'～を所有している、持っている',exampleEng:'own a house',exampleJap:'家を所有している'},
  {id:'sys_152',english:'expose',phonetic:'/ɪkˈspoʊz/',japanese:'AをBにさらす、あばく',exampleEng:'be exposed to danger',exampleJap:'危険にさらされる',derivatives:[{english:'exposure',partOfSpeech:'名',japanese:'露出、暴露'}]},
  {id:'sys_153',english:'translate',phonetic:'/trænzˈleɪt/',japanese:'～を翻訳する、変える',exampleEng:'translate a novel into English',exampleJap:'小説を英語に翻訳する',derivatives:[{english:'translation',partOfSpeech:'名',japanese:'翻訳'}]},
  {id:'sys_154',english:'cure',phonetic:'/kjʊər/',japanese:'～を治療する、悪い習慣を直す',exampleEng:'cure him of his illness',exampleJap:'彼の病気を治す'},
  {id:'sys_155',english:'perceive',phonetic:'/pərˈsiːv/',japanese:'～を知覚する、気づく、思う',exampleEng:'perceive danger',exampleJap:'危険に気づく',derivatives:[{english:'perception',partOfSpeech:'名',japanese:'知覚、認識'}]},
  {id:'sys_156',english:'adjust',phonetic:'/əˈdʒʌst/',japanese:'慣れる、適合させる、調節する',exampleEng:'adjust to a new school',exampleJap:'新しい学校に慣れる',derivatives:[{english:'adjustment',partOfSpeech:'名',japanese:'調整、適応'}]},
  {id:'sys_157',english:'alarm',phonetic:'/əˈlɑːrm/',japanese:'～をぎょっとさせる、おびえさせる',exampleEng:'be alarmed by the noise',exampleJap:'その音にぎょっとする',derivatives:[{english:'alarming',partOfSpeech:'形',japanese:'驚くべき、不安にさせる'}]},
  {id:'sys_158',english:'assist',phonetic:'/əˈsɪst/',japanese:'助ける、手伝う',exampleEng:'assist him in his work',exampleJap:'彼の仕事を手伝う',derivatives:[{english:'assistant',partOfSpeech:'名',japanese:'助手'}]},
  {id:'sys_159',english:'freeze',phonetic:'/friːz/',japanese:'凍りつく、動かなくなる',exampleEng:'a frozen stream',exampleJap:'凍った小川',derivatives:[{english:'frozen',partOfSpeech:'形',japanese:'凍った、冷凍の'}]},
  {id:'sys_160',english:'spoil',phonetic:'/spɔɪl/',japanese:'台無しにする、甘やかしてだめにする',exampleEng:'spoil the party',exampleJap:'パーティを台無しにする'},
  {id:'sys_161',english:'shift',phonetic:'/ʃɪft/',japanese:'～を変える、移す',exampleEng:'shift gears',exampleJap:'ギアを整える'},
  {id:'sys_162',english:'embarrass',phonetic:'/ɪmˈbærəs/',japanese:'～を当惑させる、恥ずかしい思いをさせる',exampleEng:'be embarrassed by the mistake',exampleJap:'そのまちがいが恥ずかしい',derivatives:[{english:'embarrassed',partOfSpeech:'形',japanese:'当惑している'}]},
  {id:'sys_163',english:'approve',phonetic:'/əˈpruːv/',japanese:'賛成する、承認する',exampleEng:'approve of their marriage',exampleJap:'2人の結婚を承認する',derivatives:[{english:'approval',partOfSpeech:'名',japanese:'賛成、承認'}]},
  {id:'sys_164',english:'weigh',phonetic:'/weɪ/',japanese:'～の重さがある、比較検討する',exampleEng:'weigh 65 kilograms',exampleJap:'65キロの重さがある',derivatives:[{english:'weight',partOfSpeech:'名',japanese:'重さ'}]},
  {id:'sys_165',english:'stretch',phonetic:'/stretʃ/',japanese:'～を広げる、伸ばす、広がる',exampleEng:'stretch my legs',exampleJap:'足を広げる'},
  {id:'sys_166',english:'participate',phonetic:'/pɑːrˈtɪsɪpeɪt/',japanese:'Aに参加する',exampleEng:'participate in the meeting',exampleJap:'会合に参加する',derivatives:[{english:'participation',partOfSpeech:'名',japanese:'参加'}]},
  {id:'sys_167',english:'exhibit',phonetic:'/ɪɡˈzɪbɪt/',japanese:'～を展示する、示す',exampleEng:'exhibit Picasso\'s works',exampleJap:'ピカソの作品を展示する',derivatives:[{english:'exhibition',partOfSpeech:'名',japanese:'展覧会、展示'}]},
  {id:'sys_168',english:'owe',phonetic:'/oʊ/',japanese:'AのことはBのおかげだ、借りている',exampleEng:'I owe my success to you.',exampleJap:'私の成功はあなたのおかげだ'},
  {id:'sys_169',english:'celebrate',phonetic:'/ˈselɪbreɪt/',japanese:'祝う、儀式を行う',exampleEng:'celebrate his birthday',exampleJap:'彼の誕生日を祝う',derivatives:[{english:'celebration',partOfSpeech:'名',japanese:'祝い'}]},
  {id:'sys_170',english:'decorate',phonetic:'/ˈdekəreɪt/',japanese:'～を装飾する、飾りをつける',exampleEng:'trees decorated with lights',exampleJap:'電球で飾られた木々',derivatives:[{english:'decoration',partOfSpeech:'名',japanese:'装飾'}]},
  {id:'sys_171',english:'forgive',phonetic:'/fərˈɡɪv/',japanese:'過ち・人を許す',exampleEng:'forgive him for being late',exampleJap:'彼の遅刻を許す'},
  {id:'sys_172',english:'seat',phonetic:'/siːt/',japanese:'座っている、収容する',exampleEng:'be seated on the bench',exampleJap:'ベンチに座っている'},
  {id:'sys_173',english:'injure',phonetic:'/ˈɪndʒər/',japanese:'～を傷つける、けがをさせる',exampleEng:'be injured in the accident',exampleJap:'その事故で負傷する',derivatives:[{english:'injury',partOfSpeech:'名',japanese:'負傷、害'}]},
  {id:'sys_174',english:'sew',phonetic:'/soʊ/',japanese:'～を縫う',exampleEng:'sew a wedding dress',exampleJap:'ウェディングドレスを縫う',derivatives:[{english:'sewing machine',partOfSpeech:'名',japanese:'ミシン'}]}
];

const DEFAULT_FOLDERS = [
  {
    id: 'folder_preset_ch1',
    name: 'システム英単語 Ch.1 🔒',
    isPreset: true,
    wordIds: []
  }
];
