/**
 * GamiWord Pro - システム英単語 Ch.1 全174語 完全データ
 */
const SYSTEM_WORDS_PRESET = [
  {id:'sys_1',english:'follow',phonetic:'/ˈfɑːloʊ/',japanese:'～の後に続く、従う',hint:'follow her advice',example:'彼女の助言に従う',derivatives:[{english:'following',partOfSpeech:'形',japanese:'次の、以下のような'}]},
  {id:'sys_2',english:'consider',phonetic:'/kənˈsɪdər/',japanese:'～を考慮する、考える',hint:'consider the problem seriously',example:'真剣にその問題を考える',derivatives:[{english:'consideration',partOfSpeech:'名',japanese:'考慮、思いやり'},{english:'considerate',partOfSpeech:'形',japanese:'思いやりのある'}]},
  {id:'sys_3',english:'increase',phonetic:'/ɪnˈkriːs/',japanese:'増える、～を増やす',hint:'increase by 20%',example:'20%増加する',derivatives:[{english:'increasingly',partOfSpeech:'副',japanese:'ますます'}]},
  {id:'sys_4',english:'expect',phonetic:'/ɪkˈspekt/',japanese:'～を予期する、期待する',hint:'expect you to arrive soon',example:'君がすぐ着くことを予期する',derivatives:[{english:'expectation',partOfSpeech:'名',japanese:'予期、期待'}]},
  {id:'sys_5',english:'decide',phonetic:'/dɪˈsaɪd/',japanese:'～することを決定する、判断する',hint:'decide to tell the truth',example:'真実を語る決意をする',derivatives:[{english:'decision',partOfSpeech:'名',japanese:'決意、決定'},{id:'decisive',partOfSpeech:'形',japanese:'決定的な、断固とした'}]},
  {id:'sys_6',english:'develop',phonetic:'/dɪˈveləp/',japanese:'～を発達させる、開発する',hint:'develop a unique ability',example:'特殊な能力を発達させる',derivatives:[{english:'development',partOfSpeech:'名',japanese:'発達、成長、開発'}]},
  {id:'sys_7',english:'provide',phonetic:'/prəˈvaɪd/',japanese:'～を供給する、与える',hint:'provide him with information',example:'彼に情報を与える',derivatives:[{english:'provision',partOfSpeech:'名',japanese:'供給、用意'}]},
  {id:'sys_8',english:'continue',phonetic:'/kənˈtɪnjuː/',japanese:'続く、～を続ける',hint:'continue to grow fast',example:'急速に成長し続ける',derivatives:[{english:'continuous',partOfSpeech:'形',japanese:'絶え間ない、休みない'}]},
  {id:'sys_9',english:'include',phonetic:'/ɪnˈkluːd/',japanese:'～を含む、含める',hint:'The list includes his name.',example:'リストは彼の名前を含んでいる',derivatives:[{english:'including',partOfSpeech:'前',japanese:'～を含めて'}]},
  {id:'sys_10',english:'remain',phonetic:'/rɪˈmeɪn/',japanese:'～のままでいる、残る',hint:'remain silent',example:'黙ったままでいる',derivatives:[{english:'remains',partOfSpeech:'名',japanese:'遺物、遺跡、残り物'}]},
  {id:'sys_11',english:'reach',phonetic:'/riːtʃ/',japanese:'～に着く、達する',hint:'reach the mountain top',example:'山頂に到達する'},
  {id:'sys_12',english:'allow',phonetic:'/əˈlaʊ/',japanese:'～を許可する、許す、可能にする',hint:'allow him to go out',example:'彼に外出を許可する',derivatives:[{english:'allowance',partOfSpeech:'名',japanese:'手当、小遣い'}]},
  {id:'sys_13',english:'force',phonetic:'/fɔːrs/',japanese:'～を強制する',hint:'be forced to work',example:'働くよう強制される'},
  {id:'sys_14',english:'offer',phonetic:'/ˈɔːfər/',japanese:'～を申し出る、与える',hint:'offer help to the poor',example:'貧しい人に援助を申し出る'},
  {id:'sys_15',english:'realize',phonetic:'/ˈriːəlaɪz/',japanese:'～を悟る、気づく、実現する',hint:'realize the error',example:'間違いを悟る',derivatives:[{english:'realization',partOfSpeech:'名',japanese:'認識、実現'}]},
  {id:'sys_16',english:'suggest',phonetic:'/səɡˈdʒest/',japanese:'～と提案する、ほのめかす',hint:'suggest a new way',example:'新しいやり方を提案する',derivatives:[{english:'suggestion',partOfSpeech:'名',japanese:'提案、暗示'}]},
  {id:'sys_17',english:'require',phonetic:'/rɪˈkwaɪər/',japanese:'～を必要とする、要求する',hint:'require more attention',example:'もっと注意を必要とする',derivatives:[{english:'requirement',partOfSpeech:'名',japanese:'要求されるもの、必要条件'}]},
  {id:'sys_18',english:'worry',phonetic:'/ˈwɜːri/',japanese:'心配する、～に心配させる',hint:'worry about money',example:'お金のことを心配する',derivatives:[{english:'worried',partOfSpeech:'形',japanese:'心配している'}]},
  {id:'sys_19',english:'wonder',phonetic:'/ˈwʌndər/',japanese:'～かと疑問に思う、驚く',hint:'wonder where he has gone',example:'彼はどこに行ったのかと思う',derivatives:[{english:'wonderful',partOfSpeech:'形',japanese:'素晴らしい'}]},
  {id:'sys_20',english:'cost',phonetic:'/kɔːst/',japanese:'（費用）を要する、～を奪う',hint:'The car cost me $50,000.',example:'その車には5万ドルかかった',derivatives:[{english:'costly',partOfSpeech:'形',japanese:'高価な、損失の大きい'}]},
  {id:'sys_21',english:'tend',phonetic:'/tend/',japanese:'Vする傾向がある、Vしがちである',hint:'tend to get angry',example:'腹を立てがちである',derivatives:[{english:'tendency',partOfSpeech:'名',japanese:'傾向、癖'}]},
  {id:'sys_22',english:'depend',phonetic:'/dɪˈpend/',japanese:'Aに依存する、Aしだいで決まる',hint:'Everything depends on him.',example:'すべては彼しだいだ',derivatives:[{english:'dependent',partOfSpeech:'形',japanese:'依存する'},{english:'dependence',partOfSpeech:'名',japanese:'依存'}]},
  {id:'sys_23',english:'share',phonetic:'/ʃeər/',japanese:'～を分け合う、共有する',hint:'share a room with a friend',example:'友人と部屋を共有する'},
  {id:'sys_24',english:'demand',phonetic:'/dɪˈmænd/',japanese:'～を要求する、必要とする',hint:'demand more freedom',example:'もっと自由を要求する',derivatives:[{english:'demanding',partOfSpeech:'形',japanese:'骨の折れる、要求の厳しい'}]},
  {id:'sys_25',english:'support',phonetic:'/səˈpɔːrt/',japanese:'～を支持する、援助する、養う',hint:'support the president',example:'大統領を支持する'},
  {id:'sys_26',english:'hire',phonetic:'/ˈhaɪər/',japanese:'～を雇う、（有料で）借りる',hint:'hire many young people',example:'多くの若者を雇う'},
  {id:'sys_27',english:'regard',phonetic:'/rɪˈɡɑːrd/',japanese:'AをBとみなす、思う',hint:'regard him as a friend',example:'彼を友達とみなす',derivatives:[{english:'regarding',partOfSpeech:'前',japanese:'～に関して'},{english:'regardless',partOfSpeech:'形',japanese:'関係なく'}]},
  {id:'sys_28',english:'base',phonetic:'/beɪs/',japanese:'AがBに基づいている',hint:'This story is based on fact.',example:'この話は事実に基づいている',derivatives:[{english:'basic',partOfSpeech:'形',japanese:'基礎的な'}]},
  {id:'sys_29',english:'improve',phonetic:'/ɪmˈpruːv/',japanese:'～を向上させる、改善する',hint:'improve living conditions',example:'生活状態を向上させる',derivatives:[{english:'improvement',partOfSpeech:'名',japanese:'進歩、改善'}]},
  {id:'sys_30',english:'recognize',phonetic:'/ˈrekəɡnaɪz/',japanese:'～を認める、識別する',hint:'recognize the importance',example:'重要性を認める',derivatives:[{english:'recognition',partOfSpeech:'名',japanese:'認識、承認'}]},
  {id:'sys_31',english:'notice',phonetic:'/ˈnoʊtɪs/',japanese:'～に気づく、～だとわかる',hint:'notice the color change',example:'色彩の変化に気づく',derivatives:[{english:'noticeable',partOfSpeech:'形',japanese:'目立つ、著しい'}]},
  {id:'sys_32',english:'suppose',phonetic:'/səˈpoʊz/',japanese:'～だと思う、想像する、仮定する',hint:'be supposed to wear a seat belt',example:'シートベルトを締めることになっている'},
  {id:'sys_33',english:'raise',phonetic:'/reɪz/',japanese:'～を上げる、育てる、提起する',hint:'raise both hands',example:'両手を上げる'},
  {id:'sys_34',english:'prefer',phonetic:'/prɪˈfɜːr/',japanese:'～をより好む',hint:'prefer tea to coffee',example:'コーヒーよりお茶を好む',derivatives:[{english:'preference',partOfSpeech:'名',japanese:'好み、好物'}]},
  {id:'sys_35',english:'cheer',phonetic:'/tʃɪər/',japanese:'～を励ます、声援する',hint:'cheer up the patients',example:'患者たちを元気づける',derivatives:[{english:'cheerful',partOfSpeech:'形',japanese:'陽気な'}]},
  {id:'sys_36',english:'suffer',phonetic:'/ˈsʌfər/',japanese:'苦しむ、（苦痛）を経験する',hint:'suffer heavy damage',example:'ひどい損害を受ける',derivatives:[{english:'suffering',partOfSpeech:'名',japanese:'苦しみ'}]},
  {id:'sys_37',english:'describe',phonetic:'/dɪˈskraɪb/',japanese:'～を描写する、特徴を説明する',hint:'describe the lost bag',example:'なくしたバッグの特徴を言う',derivatives:[{english:'description',partOfSpeech:'名',japanese:'描写、説明'}]},
  {id:'sys_38',english:'prevent',phonetic:'/prɪˈvent/',japanese:'～をさまたげる、防ぐ',hint:'prevent him from sleeping',example:'彼が眠るのをさまたげる',derivatives:[{english:'prevention',partOfSpeech:'名',japanese:'防止、予防'}]},
  {id:'sys_39',english:'reduce',phonetic:'/rɪˈduːs/',japanese:'～を減らす、変える',hint:'reduce energy costs',example:'エネルギー費を減らす',derivatives:[{english:'reduction',partOfSpeech:'名',japanese:'減少、削減'}]},
  {id:'sys_40',english:'mistake',phonetic:'/mɪˈsteɪk/',japanese:'～を誤解する、まちがえる',hint:'mistake salt for sugar',example:'塩を砂糖とまちがえる',derivatives:[{english:'mistaken',partOfSpeech:'形',japanese:'誤った、まちがっている'}]},
  {id:'sys_41',english:'prepare',phonetic:'/prɪˈpeər/',japanese:'準備をする、用意する',hint:'prepare a room for a guest',example:'客のために部屋を準備する',derivatives:[{english:'preparation',partOfSpeech:'名',japanese:'準備、用意'}]},
  {id:'sys_42',english:'encourage',phonetic:'/ɪnˈkɜːrɪdʒ/',japanese:'～をはげます、促進する',hint:'encourage children to read',example:'子供に読書をすすめる',derivatives:[{english:'encouragement',partOfSpeech:'名',japanese:'はげまし、促進'}]},
  {id:'sys_43',english:'prove',phonetic:'/pruːv/',japanese:'～だとわかる、証明する',hint:'prove to be true',example:'本当だとわかる',derivatives:[{english:'proof',partOfSpeech:'名',japanese:'証拠、証明'}]},
  {id:'sys_44',english:'treat',phonetic:'/triːt/',japanese:'～をあつかう、手当てする、おごる',hint:'treat him like a child',example:'子供みたいに彼をあつかう',derivatives:[{english:'treatment',partOfSpeech:'名',japanese:'取り扱い、治療'}]},
  {id:'sys_45',english:'establish',phonetic:'/ɪˈstæblɪʃ/',japanese:'～を設立する、確定する',hint:'establish a company',example:'会社を設立する',derivatives:[{english:'establishment',partOfSpeech:'名',japanese:'施設、組織、設立'}]},
  {id:'sys_46',english:'relate',phonetic:'/rɪˈleɪt/',japanese:'関係がある、関係づける',hint:'stress-related illness',example:'ストレスと関係のある病気',derivatives:[{english:'relation',partOfSpeech:'名',japanese:'関係'},{english:'relationship',partOfSpeech:'名',japanese:'関係'}]},
  {id:'sys_47',english:'compare',phonetic:'/kəmˈpeər/',japanese:'～を比較する、たとえる',hint:'compare Japan with China',example:'日本と中国を比較する',derivatives:[{english:'comparison',partOfSpeech:'名',japanese:'比較、たとえ'}]},
  {id:'sys_48',english:'spread',phonetic:'/spred/',japanese:'～を広げる、広がる',hint:'spread the tablecloth',example:'テーブルクロスを広げる'},
  {id:'sys_49',english:'refer',phonetic:'/rɪˈfɜːr/',japanese:'～を指し示す、言及する、参照する',hint:'What does this word refer to?',example:'この語は何を指示するか',derivatives:[{english:'reference',partOfSpeech:'名',japanese:'言及、参照'}]},
  {id:'sys_50',english:'supply',phonetic:'/səˈplaɪ/',japanese:'～を供給する、支給する',hint:'supply the city with water',example:'その都市に水を供給する'},
  {id:'sys_51',english:'gain',phonetic:'/ɡeɪn/',japanese:'～を得る、もうける、増やす',hint:'gain useful knowledge',example:'有益な知識を得る'},
  {id:'sys_52',english:'destroy',phonetic:'/dɪˈstrɔɪ/',japanese:'～を破壊する、滅ぼす',hint:'destroy forests',example:'森林を破壊する',derivatives:[{english:'destruction',partOfSpeech:'名',japanese:'破壊、破滅'}]},
  {id:'sys_53',english:'apply',phonetic:'/əˈlaɪ/',japanese:'当てはめる、応用する、申し込む',hint:'apply the rule to every case',example:'全てのケースに規則を当てはめる',derivatives:[{english:'application',partOfSpeech:'名',japanese:'応用、適用、申し込み'}]},
  {id:'sys_54',english:'seek',phonetic:'/siːk/',japanese:'～を求める、得ようとする',hint:'seek help from the police',example:'警察に助けを求める'},
  {id:'sys_55',english:'search',phonetic:'/sɜːrtʃ/',japanese:'～を探す、探る',hint:'search for the stolen car',example:'盗難車を探す'},
  {id:'sys_56',english:'claim',phonetic:'/kleɪm/',japanese:'～と主張する、言い張る、要求する',hint:'He claims that he saw a UFO.',example:'彼はUFOを見たと主張する'},
  {id:'sys_57',english:'draw',phonetic:'/drɔː/',japanese:'～を引っ張る、引き出す、描く',hint:'draw a map',example:'地図を描く',derivatives:[{english:'drawer',partOfSpeech:'名',japanese:'引き出し'}]},
  {id:'sys_58',english:'refuse',phonetic:'/rɪˈfjuːz/',japanese:'～を断る、辞退する',hint:'refuse to give up hope',example:'希望を捨てるのを拒む',derivatives:[{english:'refusal',partOfSpeech:'名',japanese:'拒否、拒絶'}]},
  {id:'sys_59',english:'respond',phonetic:'/rɪˈspɑːnd/',japanese:'返答する、反応する',hint:'respond to questions',example:'質問に答える',derivatives:[{english:'response',partOfSpeech:'名',japanese:'返答、反応'}]},
  {id:'sys_60',english:'mention',phonetic:'/ˈmenʃn/',japanese:'～について述べる、言及する',hint:'Never mention it again.',example:'二度とそのことを口にするな'},
  {id:'sys_61',english:'judge',phonetic:'/dʒʌdʒ/',japanese:'～を判断する、裁判する',hint:'judge a person by his looks',example:'人を見た目で判断する',derivatives:[{english:'judgment',partOfSpeech:'名',japanese:'判断'}]},
  {id:'sys_62',english:'approach',phonetic:'/əˈproʊtʃ/',japanese:'～に接近する、取り組む',hint:'The plane is approaching Chicago.',example:'飛行機はシカゴに接近している'},
  {id:'sys_63',english:'admit',phonetic:'/ədˈmɪt/',japanese:'～を認める、許可する',hint:'I admit that I was wrong.',example:'自分がまちがっていたと認める',derivatives:[{english:'admission',partOfSpeech:'名',japanese:'入場、入学許可'}]},
  {id:'sys_64',english:'reflect',phonetic:'/rɪˈf20t/',japanese:'～を反映する、反射する、熟考する',hint:'reflect the mood of the times',example:'時代の気分を反映する',derivatives:[{english:'reflection',partOfSpeech:'名',japanese:'反射、反映、熟考'}]},
  {id:'sys_65',english:'perform',phonetic:'/pərˈfɔːrm/',japanese:'～を行う、遂言する、演じる',hint:'perform the job',example:'仕事を遂行する',derivatives:[{english:'performance',partOfSpeech:'名',japanese:'遂行、演技、性能'}]},
  {id:'sys_66',english:'bore',phonetic:'/bɔːr/',japanese:'～をうんざりさせる、退屈させる',hint:'a very boring movie',example:'すごく退屈な映画',derivatives:[{english:'boring',partOfSpeech:'形',japanese:'退屈な'}]},
  {id:'sys_67',english:'survive',phonetic:'/sərˈvaɪv/',japanese:'生き残る、～より長生きする',hint:'survive in the jungle',example:'ジャングルで生き残る',derivatives:[{english:'survival',partOfSpeech:'名',japanese:'生存、生き残ること'}]},
  {id:'sys_68',english:'represent',phonetic:'/ˌreprɪˈzent/',japanese:'～を表す、示す、代表する',hint:'words represent ideas',example:'言葉は考えを表す',derivatives:[{english:'representative',partOfSpeech:'名',japanese:'代表者'}]},
  {id:'sys_69',english:'argue',phonetic:'/ˈɑːrɡjuː/',japanese:'～と主張する、議論する、論争する',hint:'argue that he is right',example:'彼は正しいと主張する',derivatives:[{english:'argument',partOfSpeech:'名',japanese:'議論、主張、論争'}]},
  {id:'sys_70',english:'grant',phonetic:'/ɡrænt/',japanese:'～を認める、与える',hint:'take freedom for granted',example:'自由を当然と考える'},
  {id:'sys_71',english:'indicate',phonetic:'/ˈɪndɪkeɪt/',japanese:'～を指し示す、表す',hint:'The data indicate that he is right.',example:'データは彼が正しいことを示す',derivatives:[{english:'indication',partOfSpeech:'名',japanese:'指示、暗示、兆候'}]},
  {id:'sys_72',english:'belong',phonetic:'/bɪˈlɔːŋ/',japanese:'所属している、所有物である',hint:'The book belongs to Howard.',example:'その本はハワードのものだ',derivatives:[{english:'belongings',partOfSpeech:'名',japanese:'所有物、持ち物'}]},
  {id:'sys_73',english:'acquire',phonetic:'/əˈkwaɪər/',japanese:'～を習得する、獲得する',hint:'acquire a language',example:'言語を習得する',derivatives:[{english:'acquisition',partOfSpeech:'名',japanese:'習得'}]},
  {id:'sys_74',english:'reply',phonetic:'/rɪˈplaɪ/',japanese:'返事をする、答える',hint:'reply to his letter',example:'彼の手紙に返事をする'},
  {id:'sys_75',english:'feed',phonetic:'/fiːd/',japanese:'～にエサをやる、養う',hint:'feed a large family',example:'大勢の家族を養う'},
  {id:'sys_76',english:'escape',phonetic:'/ɪˈskeɪp/',japanese:'逃げる、まぬがれる、避ける',hint:'escape from reality',example:'現実から逃避する'},
  {id:'sys_77',english:'replace',phonetic:'/rɪˈpleɪs/',japanese:'～に取って代わる、取り替える',hint:'replace the old system',example:'古い制度に取って代わる',derivatives:[{english:'replacement',partOfSpeech:'名',japanese:'取り替え、代用品'}]},
  {id:'sys_78',english:'reveal',phonetic:'/rɪˈviːl/',japanese:'～を明らかにする、示す',hint:'reveal a surprising fact',example:'驚くべき事実を明らかにする',derivatives:[{english:'revelation',partOfSpeech:'名',japanese:'暴露、発見'}]},
  {id:'sys_79',english:'surround',phonetic:'/səˈraʊnd/',japanese:'～を取り囲む',hint:'Japan is surrounded by the sea.',example:'日本は海に囲まれている',derivatives:[{english:'surroundings',partOfSpeech:'名',japanese:'環境、周囲の状況'}]},
  {id:'sys_80',english:'suit',phonetic:'/suːt/',japanese:'～に合う、適する、似合う',hint:'The job suits you.',example:'その仕事は君に合っている',derivatives:[{english:'suitable',partOfSpeech:'形',japanese:'適した、ふさわしい'}]},
  {id:'sys_81',english:'estimate',phonetic:'/ˈestɪmeɪt/',japanese:'～を推定する、評価する',hint:'the estimated population of Japan',example:'日本の推定人口',derivatives:[{english:'underestimate',partOfSpeech:'動',japanese:'～を過小評価する'}]},
  {id:'sys_82',english:'aim',phonetic:'/eɪm/',japanese:'～をねらう、目指す',hint:'aim at the Asian market',example:'アジア市場をねらう'},
  {id:'sys_83',english:'earn',phonetic:'/ɜːrn/',japanese:'～を稼ぐ、もうける、得る',hint:'earn money for the family',example:'家族のためにお金を稼ぐ'},
  {id:'sys_84',english:'decline',phonetic:'/dɪˈklaɪn/',japanese:'衰退する、低下する、辞退する',hint:'My memory began to decline.',example:'記憶力が低下し始めた'},
  {id:'sys_85',english:'afford',phonetic:'/əˈfɔːrd/',japanese:'～をする余裕がある、与える',hint:"can't afford to buy a Ford",example:'フォードの車を買う余裕がない',derivatives:[{english:'affordable',partOfSpeech:'形',japanese:'手ごろな値段の'}]},
  {id:'sys_86',english:'confuse',phonetic:'/kənˈfjuːz/',japanese:'～を当惑させる、混乱させる、混同する',hint:'be confused by her anger',example:'彼女の怒りに当惑する',derivatives:[{english:'confusion',partOfSpeech:'名',japanese:'混乱、混同、当惑'}]},
  {id:'sys_87',english:'graduate',phonetic:'/ˈɡrædʒuət/',japanese:'Aを卒業する',hint:'graduate from high school',example:'高校を卒業する',derivatives:[{english:'graduation',partOfSpeech:'名',japanese:'卒業'}]},
  {id:'sys_88',english:'vary',phonetic:'/ˈveəri/',japanese:'変わる、さまざまである、変える',hint:'vary from country to country',example:'国によって変わる',derivatives:[{english:'various',partOfSpeech:'形',japanese:'さまざまな'}]},
  {id:'sys_89',english:'remove',phonetic:'/rɪˈmuːv/',japanese:'～を移す、取り去る、脱ぐ',hint:'remove the cover',example:'カバーを取り除く',derivatives:[{english:'removal',partOfSpeech:'名',japanese:'除去、移動'}]},
  {id:'sys_90',english:'insist',phonetic:'/ɪnˈsɪst/',japanese:'～を強く主張する、言い張る',hint:'insist on going to France',example:'フランスに行くと言い張る'},
  {id:'sys_91',english:'examine',phonetic:'/ɪɡˈzæmɪn/',japanese:'～を調査する、検査する、試験する',hint:'examine every record',example:'あらゆる記録を調べる',derivatives:[{english:'examination',partOfSpeech:'名',japanese:'試験、調査'}]},
  {id:'sys_92',english:'remind',phonetic:'/rɪˈmɪnd/',japanese:'AにBのことを思い出させる',hint:'remind him of the promise',example:'彼に約束を思い出させる'},
  {id:'sys_93',english:'contribute',phonetic:'/kənˈtrɪbjuːt/',japanese:'貢献する、一因となる、寄付する',hint:'contribute to world peace',example:'世界平和に貢献する',derivatives:[{english:'contribution',partOfSpeech:'名',japanese:'貢献、寄付'}]},
  {id:'sys_94',english:'warn',phonetic:'/wɔːrn/',japanese:'人に警告する',hint:'warn him of the danger',example:'彼に危険を警告する',derivatives:[{english:'warning',partOfSpeech:'名',japanese:'警告、警報'}]},
  {id:'sys_95',english:'connect',phonetic:'/kəˈnekt/',japanese:'～をつなぐ、関係づける、つながる',hint:'connect the computer to the Internet',example:'コンピュータをインターネットにつなぐ',derivatives:[{english:'connection',partOfSpeech:'名',japanese:'結びつき、関係'}]},
  {id:'sys_96',english:'match',phonetic:'/mætʃ/',japanese:'～に匹敵する、～と調和する',hint:'match him in power',example:'力で彼に匹敵する'},
  {id:'sys_97',english:'focus',phonetic:'/ˈfoʊkəs/',japanese:'焦点を合わせる、集中する',hint:'focus on the problem',example:'その問題に焦点を合わせる'},
  {id:'sys_98',english:'reject',phonetic:'/rɪˈdʒekt/',japanese:'～を断る、拒絶する',hint:'reject the proposal',example:'提案を拒絶する',derivatives:[{english:'rejection',partOfSpeech:'名',japanese:'拒絶、拒否'}]},
  {id:'sys_99',english:'convince',phonetic:'/kənˈvɪns/',japanese:'人を納得させる、確信させる',hint:'convince him that it is true',example:'それは本当だと彼に確信させる',derivatives:[{english:'conviction',partOfSpeech:'名',japanese:'確信'}]},
  {id:'sys_100',english:'associate',phonetic:'/əˈsoʊʃieɪt/',japanese:'AをBに関連づける、連想する',hint:'Health is associated with happiness.',example:'健康は幸福と関連している',derivatives:[{english:'association',partOfSpeech:'名',japanese:'協会、連想、交際'}]},
  {id:'sys_101',english:'rush',phonetic:'/rʌʃ/',japanese:'急いで行く、急いでやる',hint:'rush into the hospital',example:'病院へ急いで行く'},
  {id:'sys_102',english:'stress',phonetic:'/stres/',japanese:'～を強調する',hint:'stress the need for information',example:'情報の必要性を強調する',derivatives:[{english:'stressful',partOfSpeech:'形',japanese:'ストレスの多い'}]},
  {id:'sys_103',english:'attract',phonetic:'/əˈtrækt/',japanese:'引きつける、魅惑する',hint:'attract his attention',example:'彼の注意を引きつける',derivatives:[{english:'attractive',partOfSpeech:'形',japanese:'魅力的な'},{english:'attraction',partOfSpeech:'名',japanese:'魅力、引きつけるもの'}]},
  {id:'sys_104',english:'rely',phonetic:'/rɪˈlaɪ/',japanese:'Aに頼る、信頼する',hint:'rely on their power',example:'彼らの力に頼る',derivatives:[{english:'reliable',partOfSpeech:'形',japanese:'信頼できる、当てになる'}]},
  {id:'sys_105',english:'regret',phonetic:'/rɪˈɡret/',japanese:'～を後悔する、残念に思う',hint:'regret leaving home',example:'家を出たのを後悔する',derivatives:[{english:'regrettable',partOfSpeech:'形',japanese:'残念な、悔やまれる'}]},
  {id:'sys_106',english:'adopt',phonetic:'/əˈdɑːpt/',japanese:'～を採用する、養子にする',hint:'adopt a new system',example:'新しいシステムを採用する',derivatives:[{english:'adoption',partOfSpeech:'名',japanese:'採用、養子縁組'}]},
  {id:'sys_107',english:'shake',phonetic:'/ʃeɪk/',japanese:'～を振る、震える、動揺させる',hint:'shake the bottle well',example:'ビンをよく振る'},
  {id:'sys_108',english:'hurt',phonetic:'/hɜːrt/',japanese:'～を傷つける、痛む',hint:'hurt her feelings',example:'彼女の気持ちを傷つける'},
  {id:'sys_109',english:'operate',phonetic:'/ˈɑːpəreɪt/',japanese:'作動する、～を操作する、手術する',hint:'operate a computer with a mouse',example:'マウスでコンピュータを操作する',derivatives:[{english:'operation',partOfSpeech:'名',japanese:'操作、手術、活動'}]},
  {id:'sys_110',english:'extend',phonetic:'/ɪkˈstend/',japanese:'～を広げる、延長する、伸びる',hint:'Exercise extends life.',example:'運動は寿命を延ばす',derivatives:[{english:'extent',partOfSpeech:'名',japanese:'程度、範囲'}]},
  {id:'sys_111',english:'blame',phonetic:'/bleɪm/',japanese:'～を非難する、～のせいにする',hint:'blame others for the failure',example:'失敗を他人のせいにする'},
  {id:'sys_112',english:'consist',phonetic:'/kənˈsɪst/',japanese:'Aで構成されている、存在している',hint:'The book consists of six lessons.',example:'その本は6課で構成されている'},
  {id:'sys_113',english:'persuade',phonetic:'/pərˈsweɪd/',japanese:'～を説得する、信じさせる',hint:'persuade them to go back',example:'彼らを説得して帰らせる',derivatives:[{english:'persuasion',partOfSpeech:'名',japanese:'説得'}]},
  {id:'sys_114',english:'admire',phonetic:'/ədˈmaɪər/',japanese:'～に感心する、賞賛する、尊敬する',hint:'admire her work',example:'彼女の仕事に感心する',derivatives:[{english:'admiration',partOfSpeech:'名',japanese:'感心、賞賛'}]},
  {id:'sys_115',english:'disappoint',phonetic:'/ˌdɪsəˈpɔɪnt/',japanese:'～を失望させる',hint:'be disappointed with the test results',example:'試験の結果に失望する',derivatives:[{english:'disappointment',partOfSpeech:'名',japanese:'失望'}]},
  {id:'sys_116',english:'expand',phonetic:'/ɪkˈspænd/',japanese:'～を拡大する、増大する、膨張する',hint:'expand business overseas',example:'海外へ事業を拡大する',derivatives:[{english:'expansion',partOfSpeech:'名',japanese:'拡大、進展'}]},
  {id:'sys_117',english:'preserve',phonetic:'/prɪˈzɜːrv/',japanese:'～を保護する、保存する、維持する',hint:'preserve forests',example:'森林を保護する',derivatives:[{english:'preservation',partOfSpeech:'名',japanese:'保護、保存、維持'}]},
  {id:'sys_118',english:'struggle',phonetic:'/ˈstrʌɡl/',japanese:'苦闘する、努力する、もがく',hint:'struggle to get free',example:'自由になろうともがく'},
  {id:'sys_119',english:'arrange',phonetic:'/əˈreɪndʒ/',japanese:'手はずを整える、手配する、配列する',hint:'arrange the meeting',example:'会合の手はずを整える',derivatives:[{english:'arrangement',partOfSpeech:'名',japanese:'準備、整理、配列'}]},
  {id:'sys_120',english:'disturb',phonetic:'/dɪˈstɜːrb/',japanese:'～をさまたげる、不安にする',hint:'disturb his sleep',example:'彼の睡眠をさまたげる',derivatives:[{english:'disturbance',partOfSpeech:'名',japanese:'混乱、妨害'}]},
  {id:'sys_121',english:'employ',phonetic:'/ɪmˈplɔɪ/',japanese:'～を雇う、用いる',hint:'employ foreign workers',example:'外国人労働者を雇う',derivatives:[{english:'employee',partOfSpeech:'名',japanese:'従業員'},{english:'employment',partOfSpeech:'名',japanese:'雇用、職'}]},
  {id:'sys_122',english:'engage',phonetic:'/ɪnˈɡeɪdʒ/',japanese:'Aに従事する、参加する、従事させる',hint:'engage in volunteer activities',example:'ボランティア活動に従事する',derivatives:[{english:'engagement',partOfSpeech:'名',japanese:'約束、婚約'}]},
  {id:'sys_123',english:'abandon',phonetic:'/əˈbændən/',japanese:'～を捨てる、放棄する',hint:'an abandoned pet',example:'捨てられたペット'},
  {id:'sys_124',english:'display',phonetic:'/dɪˈspleɪ/',japanese:'～を展示する、表す、表示する',hint:'display prices',example:'価格を示す'},
  {id:'sys_125',english:'encounter',phonetic:'/ɪnˈkaʊntər/',japanese:'～に偶然出会う、遭う、ぶつかる',hint:'encounter many difficulties',example:'数々の困難に出会う'},
  {id:'sys_126',english:'amuse',phonetic:'/əˈmjuːz/',japanese:'～を楽しませる、笑わせる',hint:'amuse students with jokes',example:'冗談で学生を笑わせる',derivatives:[{english:'amusing',partOfSpeech:'形',japanese:'ゆかいな、楽しい'}]},
  {id:'sys_127',english:'bother',phonetic:'/ˈbɑːðər/',japanese:'面倒をかける、気にする',hint:'Sorry to bother you, but...',example:'おじゃましてすみませんが…'},
  {id:'sys_128',english:'concentrate',phonetic:'/ˈkɑːnsntreɪt/',japanese:'集中する、集中させる',hint:'concentrate on what he is saying',example:'彼の話に集中する',derivatives:[{english:'concentration',partOfSpeech:'名',japanese:'集中、専念'}]},
  {id:'sys_129',english:'adapt',phonetic:'/əˈdæpt/',japanese:'～を適応させる、適応する、改変する',hint:'adapt to a new culture',example:'新しい文化に適応する',derivatives:[{english:'adaptation',partOfSpeech:'名',japanese:'適応、順順'}]},
  {id:'sys_130',english:'puzzle',phonetic:'/ˈpʌzl/',japanese:'～を当惑させる、困らせる',hint:'be puzzled by the problem',example:'その問題に頭を悩ませる',derivatives:[{english:'puzzled',partOfSpeech:'形',japanese:'当惑して'}]},
  {id:'sys_131',english:'appeal',phonetic:'/əˈpiːl/',japanese:'Aに訴えかける、引きつける',hint:'appeal to his feelings',example:'彼の感情に訴えかける',derivatives:[{english:'appealing',partOfSpeech:'形',japanese:'魅力的な'}]},
  {id:'sys_132',english:'combine',phonetic:'/kəmˈbaɪn/',japanese:'～を結合させる、組み合わせる',hint:'combine song and dance',example:'歌と踊りを組み合わせる',derivatives:[{english:'combination',partOfSpeech:'名',japanese:'結合、組み合わせ'}]},
  {id:'sys_133',english:'delay',phonetic:'/dɪˈleɪ/',japanese:'～を遅らせる、延期する',hint:'delay his arrival',example:'彼の到着を遅らせる'},
  {id:'sys_134',english:'repair',phonetic:'/rɪˈpeər/',japanese:'～を修理する、修復する',hint:'repair the car',example:'車を修理する'},
  {id:'sys_135',english:'fascinate',phonetic:'/ˈfæsɪneɪt/',japanese:'人を夢中にさせる、興味をかきたてる',hint:'a fascinating story',example:'夢中にさせる物語',derivatives:[{english:'fascinating',partOfSpeech:'形',japanese:'魅惑的な、非常におもしろい'}]},
  {id:'sys_136',english:'pardon',phonetic:'/ˈpɑːrdn/',japanese:'～を許す',hint:'Pardon me.',example:'ごめんなさい'},
  {id:'sys_137',english:'import',phonetic:'/ˈɪmpɔːrt/',japanese:'～を輸入する',hint:'import food from abroad',example:'海外から食料を輸入する'},
  {id:'sys_138',english:'remark',phonetic:'/rɪˈmɑːrk/',japanese:'～と述べる、言う',hint:'remark that he is kind',example:'彼は親切だと述べる',derivatives:[{english:'remarkable',partOfSpeech:'形',japanese:'注目すべき、珍しい'}]},
  {id:'sys_139',english:'reserve',phonetic:'/rɪˈzɜːrv/',japanese:'～を予約する、とっておく',hint:'reserve a room at a hotel',example:'ホテルの部屋を予約する',derivatives:[{english:'reservation',partOfSpeech:'名',japanese:'予約、指定'}]},
  {id:'sys_140',english:'amaze',phonetic:'/əˈmeɪz/',japanese:'～を驚嘆させる',hint:'at an amazing speed',example:'驚異的な速さで',derivatives:[{english:'amazing',partOfSpeech:'形',japanese:'驚くべき、見事な'}]},
  {id:'sys_141',english:'frighten',phonetic:'/ˈfraɪtn/',japanese:'人におびえさせる、ぞっとさせる',hint:'a frightening experience',example:'ぞっとするような経験',derivatives:[{english:'frightening',partOfSpeech:'形',japanese:'ぞっとするような'}]},
  {id:'sys_142',english:'release',phonetic:'/rɪˈliːs/',japanese:'～を解放する、発表する、放出する',hint:'release him from work',example:'仕事から彼を解放する'},
  {id:'sys_143',english:'rent',phonetic:'/rent/',japanese:'～を賃借りする、賃貸しする',hint:'rent an apartment',example:'アパートを借りる'},
  {id:'sys_144',english:'recover',phonetic:'/rɪˈkʌvər/',japanese:'回復する、取り戻す',hint:'recover from illness',example:'病気から回復する',derivatives:[{english:'recovery',partOfSpeech:'名',japanese:'回復、取り戻すこと'}]},
  {id:'sys_145',english:'suspect',phonetic:'/səˈspekt/',japanese:'～ではないかと思う、疑う',hint:'I suspect that he is a spy.',example:'私は彼がスパイではないかと思う',derivatives:[{english:'suspicion',partOfSpeech:'名',japanese:'容疑、疑い'}]},
  {id:'sys_146',english:'deliver',phonetic:'/dɪˈlɪvər/',japanese:'～を配達する、渡す、演説をする',hint:'deliver a message to a friend',example:'友人に伝言を渡す',derivatives:[{english:'delivery',partOfSpeech:'名',japanese:'配達'}]},
  {id:'sys_147',english:'identify',phonetic:'/aɪˈdentɪfaɪ/',japanese:'正体をつきとめる、共感する、同一視する',hint:'identify people by their eyes',example:'目で人の本人確認をする',derivatives:[{english:'identity',partOfSpeech:'名',japanese:'身元、正体、独自性'}]},
  {id:'sys_148',english:'locate',phonetic:'/ˈloʊkeɪt/',japanese:'位置する、場所を見つける',hint:'The office is located in the area.',example:'オフィスはその地域にある',derivatives:[{english:'location',partOfSpeech:'名',japanese:'位置、場所'}]},
  {id:'sys_149',english:'manufacture',phonetic:'/ˌmænjuˈfæktʃər/',japanese:'～を製造する、生産する',hint:'a car manufacturing company',example:'車を製造する会社',derivatives:[{english:'manufacturer',partOfSpeech:'名',japanese:'製造業者、メーカー'}]},
  {id:'sys_150',english:'occupy',phonetic:'/ˈːkjupaɪ/',japanese:'場所・地位などを占める',hint:'occupy a high position',example:'高い地位を占める'},
  {id:'sys_151',english:'own',phonetic:'/oʊn/',japanese:'～を所有している、持っている',hint:'own a house',example:'家を所有している'},
  {id:'sys_152',english:'expose',phonetic:'/ɪkˈspoʊz/',japanese:'AをBにさらす、あばく',hint:'be exposed to danger',example:'危険にさらされる',derivatives:[{english:'exposure',partOfSpeech:'名',japanese:'露出、暴露'}]},
  {id:'sys_153',english:'translate',phonetic:'/trænzˈleɪt/',japanese:'～を翻訳する、変える',hint:'translate a novel into English',example:'小説を英語に翻訳する',derivatives:[{english:'translation',partOfSpeech:'名',japanese:'翻訳'}]},
  {id:'sys_154',english:'cure',phonetic:'/kjʊər/',japanese:'～を治療する、悪い習慣を直す',hint:'cure him of his illness',example:'彼の病気を治す'},
  {id:'sys_155',english:'perceive',phonetic:'/pərˈsiːv/',japanese:'～を知覚する、気づく、思う',hint:'perceive danger',example:'危険に気づく',derivatives:[{english:'perception',partOfSpeech:'名',japanese:'知覚、認識'}]},
  {id:'sys_156',english:'adjust',phonetic:'/əˈdʒʌst/',japanese:'慣れる、適合させる、調節する',hint:'adjust to a new school',example:'新しい学校に慣れる',derivatives:[{english:'adjustment',partOfSpeech:'名',japanese:'調整、適応'}]},
  {id:'sys_157',english:'alarm',phonetic:'/əˈlɑːrm/',japanese:'～をぎょっとさせる、おびえさせる',hint:'be alarmed by the noise',example:'その音にぎょっとする',derivatives:[{english:'alarming',partOfSpeech:'形',japanese:'驚くべき、不安にさせる'}]},
  {id:'sys_158',english:'assist',phonetic:'/əˈsɪst/',japanese:'助ける、手伝う',hint:'assist him in his work',example:'彼の仕事を手伝う',derivatives:[{english:'assistant',partOfSpeech:'名',japanese:'助手'}]},
  {id:'sys_159',english:'freeze',phonetic:'/friːz/',japanese:'凍りつく、動かなくなる',hint:'a frozen stream',example:'凍った小川',derivatives:[{english:'frozen',partOfSpeech:'形',japanese:'凍った、冷凍の'}]},
  {id:'sys_160',english:'spoil',phonetic:'/spɔɪl/',japanese:'台無しにする、甘やかしてだめにする',hint:'spoil the party',example:'パーティを台無しにする'},
  {id:'sys_161',english:'shift',phonetic:'/ʃɪft/',japanese:'～を変える、移す',hint:'shift gears',example:'ギアを整える'},
  {id:'sys_162',english:'embarrass',phonetic:'/ɪmˈbærəs/',japanese:'～を当惑させる、恥ずかしい思いをさせる',hint:'be embarrassed by the mistake',example:'そのまちがいが恥ずかしい',derivatives:[{english:'embarrassed',partOfSpeech:'形',japanese:'当惑している'}]},
  {id:'sys_163',english:'approve',phonetic:'/əˈpruːv/',japanese:'賛成する、承認する',hint:'approve of their marriage',example:'2人の結婚を承認する',derivatives:[{english:'approval',partOfSpeech:'名',japanese:'賛成、承認'}]},
  {id:'sys_164',english:'weigh',phonetic:'/weɪ/',japanese:'～の重さがある、比較検討する',hint:'weigh 65 kilograms',example:'65キロの重さがある',derivatives:[{english:'weight',partOfSpeech:'名',japanese:'重さ'}]},
  {id:'sys_165',english:'stretch',phonetic:'/stretʃ/',japanese:'～を広げる、伸ばす、広がる',hint:'stretch my legs',example:'足を広げる'},
  {id:'sys_166',english:'participate',phonetic:'/pɑːrˈtɪsɪpeɪt/',japanese:'Aに参加する',hint:'participate in the meeting',example:'会合に参加する',derivatives:[{english:'participation',partOfSpeech:'名',japanese:'参加'}]},
  {id:'sys_167',english:'exhibit',phonetic:'/ɪɡˈzɪbɪt/',japanese:'～を展示する、示す',hint:'exhibit Picasso\'s works',example:'ピカソの作品を展示する',derivatives:[{english:'exhibition',partOfSpeech:'名',japanese:'展覧会、展示'}]},
  {id:'sys_168',english:'owe',phonetic:'/oʊ/',japanese:'AのことはBのおかげだ、借りている',hint:'I owe my success to you.',example:'私の成功はあなたのおかげだ'},
  {id:'sys_169',english:'celebrate',phonetic:'/ˈselɪbreɪt/',japanese:'祝う、儀式を行う',hint:'celebrate his birthday',example:'彼の誕生日を祝う',derivatives:[{english:'celebration',partOfSpeech:'名',japanese:'祝い'}]},
  {id:'sys_170',english:'decorate',phonetic:'/ˈdekəreɪt/',japanese:'～を装飾する、飾りをつける',hint:'trees decorated with lights',example:'電球で飾られた木々',derivatives:[{english:'decoration',partOfSpeech:'名',japanese:'装飾'}]},
  {id:'sys_171',english:'forgive',phonetic:'/fərˈɡɪv/',japanese:'過ち・人を許す',hint:'forgive him for being late',example:'彼の遅刻を許す'},
  {id:'sys_172',english:'seat',phonetic:'/siːt/',japanese:'座っている、収容する',hint:'be seated on the bench',example:'ベンチに座っている'},
  {id:'sys_173',english:'injure',phonetic:'/ˈɪndʒər/',japanese:'～を傷つける、けがをさせる',hint:'be injured in the accident',example:'その事故で負傷する',derivatives:[{english:'injury',partOfSpeech:'名',japanese:'負傷、害'}]},
  {id:'sys_174',english:'sew',phonetic:'/soʊ/',japanese:'～を縫う',hint:'sew a wedding dress',example:'ウェディングドレスを縫う',derivatives:[{english:'sewing machine',partOfSpeech:'名',japanese:'ミシン'}]}
];

const DEFAULT_FOLDERS = [
  {
    id: 'folder_preset_ch1',
    name: 'システム英単語 Ch.1 🔒',
    isPreset: true,
    wordIds: []
  }
];
